# Generated by Django 3.2.18 on 2023-03-14 00:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='answered', to='polls.question'),
        ),
        migrations.AlterField(
            model_name='point',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='respondent', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
