# Generated by Django 3.2.18 on 2023-03-12 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20230313_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='votes',
            field=models.PositiveIntegerField(default=0, verbose_name='Голосов'),
        ),
    ]
