# Generated by Django 3.2.18 on 2023-03-12 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_choice_votes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='point',
            options={'ordering': ['points'], 'verbose_name_plural': 'Баллы пользователей'},
        ),
        migrations.RemoveField(
            model_name='point',
            name='choice',
        ),
    ]
